[service]
deployment = "dev"
environment = "development"
logging_level = "info"

[infisical.connection]
url_schema = "http"
host = "127.0.0.1"
port = 80

[infisical.auth]
client_id = "a68d6548-c1ce-42c5-854c-acec188b7b16"

[infisical.project]
project_id = "f518625c-5ab2-479d-b800-0c930567020b"
env_slug = "dev"
secret_path = "/"

[database]
url_schema = "postgresql+asyncpg"
host = "127.0.0.1"
port = 5432
database = "telegram_user_app_db"
username = "admin"
