version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/src/news_analysis_service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "uv"
    directory: "/src/telegram_user_app_service"
    schedule:
      interval: "weekly"
