"""subscriptions token table created.

Revision ID: 9b90143ae775
Revises: 2d14726b9fbe
Create Date: 2026-05-14 20:57:03.066037

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b90143ae775"
down_revision: str | Sequence[str] | None = "2d14726b9fbe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("subscription_tokens_user_id_fkey"), "subscription_tokens", type_="foreignkey")
    op.create_foreign_key(None, "subscription_tokens", "users", ["user_id"], ["id"])
    op.drop_column("subscription_tokens", "chat_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscription_tokens", sa.Column("chat_id", sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "subscription_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("subscription_tokens_user_id_fkey"),
        "subscription_tokens",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
