"""make it possible to delete user without deleting tokens.

Revision ID: c3a6f2e990cd
Revises: 9b90143ae775
Create Date: 2026-05-14 21:51:43.334649

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3a6f2e990cd"
down_revision: str | Sequence[str] | None = "9b90143ae775"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("subscription_tokens_user_id_fkey"), "subscription_tokens", type_="foreignkey")
    op.create_foreign_key(None, "subscription_tokens", "users", ["user_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscription_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("subscription_tokens_user_id_fkey"), "subscription_tokens", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
