"""Union type definitions for AI service interactions."""

from typing import Annotated

from pydantic import BaseModel, Field

from src.models.analysis_filters import filters_list
from src.settings.models.settings_model import OllamaSupportedModels, QwenSupportedModels


class AnalyzeContentRequest(BaseModel):
    """Request model for content analysis by the AI service."""

    model: Annotated[
        OllamaSupportedModels | QwenSupportedModels,
        Field(
            ...,
            title="The AI model to use for content analysis (depends on the deployment)",
        ),
    ]
    prompt: Annotated[
        str,
        Field(..., title="The prompt to send to the AI model for content analysis"),
    ]
    system_prompt: Annotated[
        str | None,
        Field(
            None,
            title=(
                "Static instructions sent as a separate system message, kept identical "
                "across requests so the model server can reuse its cached prefix"
            ),
        ),
    ] = None


class OllamaAnalyzeContentRequest(AnalyzeContentRequest):
    """Request model for content analysis using the Ollama API."""

    model: Annotated[
        OllamaSupportedModels,
        Field(
            ...,
            title="The Ollama AI model to use for content analysis",
        ),
    ]


class QwenAnalyzeContentRequest(AnalyzeContentRequest):
    """Request model for content analysis using the Qwen API."""

    model: Annotated[
        QwenSupportedModels,
        Field(
            ...,
            title="The Qwen AI model to use for content analysis",
        ),
    ]


class MentionedCompany(BaseModel):
    """Model representing a company named in the news article and its role in the story."""

    name: Annotated[
        str,
        Field(
            ...,
            title="The base (nominative) name of the company as it appears in the news article",
        ),
    ]
    context: Annotated[
        str,
        Field(
            ...,
            title="One sentence describing what the news article says about this company",
        ),
    ]


class StructuredOutputResponse(BaseModel):
    """Response model for structured output from the AI service."""

    title: Annotated[
        str,
        Field(
            ...,
            title="The title of the news article translated by the AI model",
        ),
    ]
    source: Annotated[
        str,
        Field(
            ...,
            title="The source of the news article as determined by the AI model",
        ),
    ]
    published_at: Annotated[
        str,
        Field(
            ...,
            title="The date and time when the news article was published",
        ),
    ]
    summary: Annotated[
        str,
        Field(
            ...,
            title="The summary of the news article generated by the AI model",
        ),
    ]
    mentioned_companies: Annotated[
        list[MentionedCompany],
        Field(
            ...,
            title="The companies mentioned in the news article, each with the context of its involvement",
        ),
    ]
    affected_sectors: Annotated[
        list[filters_list],
        Field(
            ...,
            title="The industries and themes the news article concerns",
        ),
    ]


class AnalyzeContentResponse(BaseModel):
    """Response model for content analysis results from the AI service."""

    response: Annotated[
        StructuredOutputResponse | str,
        Field(
            ...,
            title="The generated response from the AI model based on the provided prompt",
        ),
    ]
