"""Union type definitions for AI service interactions."""

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field

from src.models.analysis_filters import filters_list
from src.settings.models.settings_model import OllamaSupportedModels, QwenSupportedModels


class MarketTakeawaysSentiment(StrEnum):
    """Enum representing the sentiment of market takeaways."""

    STRONGPOSITIVE = "strong positive"
    POSITIVE = "positive"
    NEGATIVE = "negative"
    STRONGNEGATIVE = "strong negative"


class SignificanceLevel(StrEnum):
    """Enum representing the significance level of news."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    UNRELATED = "unrelated"


class AnalyzeContentRequest(BaseModel):
    """Request model for content analysis by the AI service."""

    model: Annotated[
        OllamaSupportedModels | QwenSupportedModels,
        Field(
            ...,
            title="The AI model to use for content analysis (depends on the deployment)",
        ),
    ]
    prompt: Annotated[
        str,
        Field(..., title="The prompt to send to the AI model for content analysis"),
    ]


class OllamaAnalyzeContentRequest(AnalyzeContentRequest):
    """Request model for content analysis using the Ollama API."""

    model: Annotated[
        OllamaSupportedModels,
        Field(
            ...,
            title="The Ollama AI model to use for content analysis",
        ),
    ]


class QwenAnalyzeContentRequest(AnalyzeContentRequest):
    """Request model for content analysis using the Qwen API."""

    model: Annotated[
        QwenSupportedModels,
        Field(
            ...,
            title="The Qwen AI model to use for content analysis",
        ),
    ]


class MarketTakeaways(BaseModel):
    """Model representing the market takeaways generated by the AI service."""

    impact: Annotated[
        str,
        Field(
            ...,
            title="One concrete forward-looking sentence about the likely market movement based on the news article",
        ),
    ]
    sector: Annotated[
        filters_list,
        Field(
            ...,
            title="The sector which is likely to be affected by the news based on the AI model's analysis",
        ),
    ]
    sentiment: Annotated[
        MarketTakeawaysSentiment,
        Field(
            ...,
            title="The sentiment of the market takeaway as determined by the AI model",
        ),
    ]


class StructuredOutputResponse(BaseModel):
    """Response model for structured output from the AI service."""

    title: Annotated[
        str,
        Field(
            ...,
            title="The title of the news article translated by the AI model",
        ),
    ]
    source: Annotated[
        str,
        Field(
            ...,
            title="The source of the news article as determined by the AI model",
        ),
    ]
    published_at: Annotated[
        str,
        Field(
            ...,
            title="The date and time when the news article was published",
        ),
    ]
    summary: Annotated[
        str,
        Field(
            ...,
            title="The summary of the news article generated by the AI model",
        ),
    ]
    market_takeaways: Annotated[
        list[MarketTakeaways],
        Field(
            ...,
            title="The market takeaways generated by the AI model",
        ),
    ]
    mentioned_companies: Annotated[
        list[str],
        Field(
            ...,
            title="The companies mentioned in the news article",
        ),
    ]
    affected_sectors: Annotated[
        list[filters_list],
        Field(
            ...,
            title="The sectors affected by the news article as determined by the AI model",
        ),
    ]
    significance: Annotated[
        SignificanceLevel,
        Field(
            ...,
            title="The significance of the news article as determined by the AI model",
        ),
    ]


class AnalyzeContentResponse(BaseModel):
    """Response model for content analysis results from the AI service."""

    response: Annotated[
        StructuredOutputResponse | str,
        Field(
            ...,
            title="The generated response from the AI model based on the provided prompt",
        ),
    ]
