"""This module defines the various filters that can be applied to the news articles for analysis."""

from typing import Literal

equity_sectors_list = Literal[
    "Banking",
    "Insurance",
    "Fintech",
    "Energy",
    "Oil and gas",
    "Renewables",
    "Mining",
    "Metals and steel",
    "Technology",
    "Semiconductors",
    "Software",
    "Cybersecurity",
    "Retail",
    "E-commerce",
    "Luxury",
    "Healthcare",
    "Pharma",
    "Biotech",
    "Real estate",
    "Construction",
    "Utilities",
    "Water",
    "Telecom",
    "Media",
    "Gaming",
    "Food and beverage",
    "Agriculture",
    "Automotive",
    "Aerospace and defense",
    "Chemicals",
    "Logistics",
    "Shipping",
    "Transportation",
    "Travel and leisure",
    "Hospitality",
    "Education",
    "Sports",
    "Entertainment",
    "Fashion",
    "Beauty",
    "Personal care",
    "Consumer goods",
    "Industrial goods",
    "Capital goods",
    "Conglomerates",
]
commodities_list = Literal[
    "Oil",
    "Natural gas",
    "Coal",
    "Gold",
    "Silver",
    "Copper",
    "Aluminum",
    "Lithium",
    "Iron ore",
    "Uranium",
    "Wheat",
    "Corn",
    "Soybeans",
    "Coffee",
    "Cotton",
    "Sugar",
    "Livestock",
    "Cocoa",
]
asset_classes_and_macro_themes_list = Literal[
    "Commodities",
    "Currency",
    "Forex",
    "Crypto",
    "Bonds",
    "Equities",
    "Indices",
    "Inflation",
    "Interest rates",
    "Fiscal policy",
    "Geopolitics",
    "Trade",
    "Sanctions",
    "Regulation",
]
special = Literal["UNRELATED"]

filters_list = equity_sectors_list | commodities_list | asset_classes_and_macro_themes_list | special
