"""Models for interacting with the Ollama API."""

from datetime import datetime
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, field_serializer

from src.settings.models.settings_model import OllamaSupportedModels

Base64Str = Annotated[str, Field(..., title="Base64-encoded string")]


class OllamaCompletionRequest(BaseModel):
    """Request model for generating completions using the Ollama API.

    References: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion
    """

    model: Annotated[OllamaSupportedModels, Field(..., title="Ollama Model")]
    prompt: Annotated[str, Field(..., title="Prompt for the model to generate a response to")]
    suffix: Annotated[str | None, Field(None, title="Optional suffix to append to the generated response")] = None
    images: Annotated[
        list[Base64Str] | None, Field(None, title="Optional list of Base64-encoded images to include in the prompt")
    ] = None
    think: Annotated[
        bool, Field(False, title="Whether to include 'thinking' steps in the response generation process")
    ] = False
    format: Annotated[str | None, Field(None, title="The format of the response. Check docs for examples.")] = None
    stream: Annotated[
        bool, Field(False, title="Whether to stream the response as it's generated (if supported by the model)")
    ] = False

    model_config = ConfigDict(extra="ignore")


class OllamaCompletionResponse(BaseModel):
    """Response model for completions generated by the Ollama API.

    References: https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion
    """

    model: Annotated[OllamaSupportedModels, Field(..., title="The model that generated the response")]
    created_at: Annotated[datetime, Field(..., title="The timestamp when the response was created")]
    response: Annotated[str, Field(..., title="The generated response from the model")]
    done: Annotated[bool, Field(..., title="Whether the response generation is complete")]

    model_config = ConfigDict(extra="ignore")

    @field_serializer("created_at")
    def serialize_dt(self, dt: datetime, _info: Any) -> str:
        """Serialize the datetime object to an ISO 8601 string format."""
        return dt.isoformat()


class OllamaModelsResponse(BaseModel):
    """Response model for one available model from the Ollama API.

    References: https://github.com/ollama/ollama/blob/main/docs/api.md#list-local-models
    """

    name: Annotated[str, Field(..., title="The name of the model deployment")]
    model: Annotated[OllamaSupportedModels, Field(..., title="The name of the model")]
    modified_at: Annotated[datetime, Field(..., title="The timestamp when the model deployment was last modified")]
    size: Annotated[int, Field(..., title="The size of the model deployment")]
    digest: Annotated[str, Field(..., title="The digest of the model deployment")]

    model_config = ConfigDict(extra="ignore")

    @field_serializer("modified_at")
    def serialize_dt(self, dt: datetime, _info: Any) -> str:
        """Serialize the datetime object to an ISO 8601 string format."""
        return dt.isoformat()


class OllamaTagsResponse(BaseModel):
    """Response model for the list of available models from the Ollama API.

    References: https://github.com/ollama/ollama/blob/main/docs/api.md#list-local-models
    """

    models: Annotated[list[OllamaModelsResponse], Field(..., title="The list of available model deployments")]

    model_config = ConfigDict(extra="ignore")
