"""Pydantic models for Qwen API interactions (OpenAI Compatible)."""

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from src.settings.models.settings_model import QwenSupportedModels


class ChatMessageRole(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"

class ChatMessage(BaseModel):
    """A message in a chat conversation."""

    role: Annotated[
        ChatMessageRole,
        Field(..., title="The role of the messages author"),
    ]
    content: Annotated[str, Field(..., title="The contents of the message")]


class QwenCompletionRequest(BaseModel):
    """Request model for generating chat completions using the OpenAI-compatible Qwen API.

    References: https://developers.openai.com/api/reference/resources/chat/subresources/completions
    """

    model: Annotated[QwenSupportedModels, Field(..., title="Qwen Model")]
    messages: Annotated[list[ChatMessage], Field(..., title="A list of messages comprising the conversation so far")]
    temperature: Annotated[
        float | None,
        Field(None, title="What sampling temperature to use, between 0 and 2"),
    ] = 0
    stream: Annotated[
        bool,
        Field(
            False,
            title="If set, partial message deltas will be sent, like in ChatGPT.",
        ),
    ] = False

    model_config = ConfigDict(extra="ignore")


class Choice(BaseModel):
    """A chat completion choice generated by the model."""

    index: Annotated[int, Field(..., title="The index of the choice in the list of choices")]
    message: Annotated[ChatMessage, Field(..., title="A chat completion message generated by the model")]
    finish_reason: Annotated[
        str | None,
        Field(None, title="The reason the model stopped generating tokens"),
    ] = None

    model_config = ConfigDict(extra="ignore")


class QwenCompletionResponse(BaseModel):
    """Response model for chat completions generated by the OpenAI-compatible API.

    References: https://developers.openai.com/api/reference/resources/chat/subresources/completions
    """

    id: Annotated[str, Field(..., title="A unique identifier for the chat completion")]
    object: Annotated[Literal["chat.completion"], Field("chat.completion", title="The object type")]
    created: Annotated[int, Field(..., title="The Unix timestamp (in sec) of when the chat completion was created")]
    model: Annotated[str, Field(..., title="The model used for the chat completion")]
    choices: Annotated[list[Choice], Field(..., title="A list of chat completion choices")]

    model_config = ConfigDict(extra="ignore")


class QwenModelData(BaseModel):
    """Data object for a single model from the API.

    References: https://developers.openai.com/api/reference/resources/models
    """

    id: Annotated[QwenSupportedModels, Field(..., title="The model identifier, which can be referenced in the API endpoints")]
    object: Annotated[Literal["model"], Field("model", title="The object type, which is always 'model'")]
    created: Annotated[int, Field(..., title="The Unix timestamp (in seconds) when the model was created")]
    owned_by: Annotated[str, Field(..., title="The organization that owns the model")]

    model_config = ConfigDict(extra="ignore")


class QwenModelsResponse(BaseModel):
    """Response model for the list of available models from the OpenAI-compatible API.

    References: https://developers.openai.com/api/reference/resources/models/methods/list
    """

    object: Annotated[Literal["list"], Field("list", title="The object type")]
    data: Annotated[
        list[QwenModelData],
        Field(..., title="The list of available models"),
    ]

    model_config = ConfigDict(extra="ignore")
