"""Module defining the data models for news items and their associated metadata."""

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class MarketTakeaways(BaseModel):
    """Model representing the market takeaways generated by the AI service."""

    impact: Annotated[
        str,
        Field(
            ...,
            title="One concrete forward-looking sentence about the likely market movement based on the news article",
        ),
    ]
    sector: Annotated[
        str,
        Field(
            ...,
            title="The sector which is likely to be affected by the news based on the AI model's analysis",
        ),
    ]
    sentiment: Annotated[
        str,
        Field(
            ...,
            title="The sentiment of the market takeaway as determined by the AI model",
        ),
    ]


class StructuredOutputResponse(BaseModel):
    """Response model for structured output from the AI service."""

    title: Annotated[
        str,
        Field(
            ...,
            title="The title of the news article translated by the AI model",
        ),
    ]
    source: Annotated[
        str,
        Field(
            ...,
            title="The source of the news article as determined by the AI model",
        ),
    ]
    published_at: Annotated[
        str,
        Field(
            ...,
            title="The date and time when the news article was published",
        ),
    ]
    summary: Annotated[
        str,
        Field(
            ...,
            title="The summary of the news article generated by the AI model",
        ),
    ]
    market_takeaways: Annotated[
        list[MarketTakeaways],
        Field(
            ...,
            title="The market takeaways generated by the AI model",
        ),
    ]

    model_config = ConfigDict(extra="ignore")


class NewsItem(BaseModel):
    """Model representing a parsed news item."""

    link: Annotated[str, Field(title="Link", description="The URL of the news item")]
    response: Annotated[
        StructuredOutputResponse | str | None,
        Field(None, title="Response", description="Response generated by LLM model"),
    ] = None

    model_config = ConfigDict(extra="ignore")
