"""Module defining the data models for news items and their associated metadata."""

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class MentionedCompany(BaseModel):
    """Model representing a company named in the news article and its role in the story."""

    name: Annotated[
        str,
        Field(
            ...,
            title="The base (nominative) name of the company as it appears in the news article",
        ),
    ]
    context: Annotated[
        str,
        Field(
            ...,
            title="One sentence describing what the news article says about this company",
        ),
    ]

    model_config = ConfigDict(extra="ignore")


class StructuredOutputResponse(BaseModel):
    """Response model for structured output from the AI service."""

    title: Annotated[
        str,
        Field(
            ...,
            title="The title of the news article translated by the AI model",
        ),
    ]
    source: Annotated[
        str,
        Field(
            ...,
            title="The source of the news article as determined by the AI model",
        ),
    ]
    published_at: Annotated[
        str,
        Field(
            ...,
            title="The date and time when the news article was published",
        ),
    ]
    summary: Annotated[
        str,
        Field(
            ...,
            title="The summary of the news article generated by the AI model",
        ),
    ]
    mentioned_companies: Annotated[
        list[MentionedCompany],
        Field(
            ...,
            title="The companies mentioned in the news article, each with the context of its involvement",
        ),
    ]
    affected_sectors: Annotated[
        list[str],
        Field(
            ...,
            title="The industries and themes the news article concerns",
        ),
    ]

    model_config = ConfigDict(extra="ignore")


class NewsItem(BaseModel):
    """Model representing a parsed news item."""

    link: Annotated[str, Field(title="Link", description="The URL of the news item")]
    response: Annotated[
        StructuredOutputResponse | str | None,
        Field(None, title="Response", description="Response generated by LLM model"),
    ] = None

    model_config = ConfigDict(extra="ignore")
