services:
  infisical-backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      infisical-db:
        condition: service_healthy
      infisical-redis:
        condition: service_started
    image: infisical/infisical:v0.159.8
    pull_policy: always
    env_file: .infisical.env
    ports:
      - 80:8080
    environment:
      - NODE_ENV=development
    networks:
      - infisical

  infisical-redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: .infisical.env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - infisical
    volumes:
      - redis_data:/data

  infisical-db:
    container_name: infisical-db
    image: postgres:18.3-alpine3.23
    restart: always
    env_file: .infisical.env
    volumes:
      - infisical_pg_data:/var/lib/postgresql/data
    networks:
      - infisical
    healthcheck:
      test: "pg_isready --username=$${POSTGRES_USER} && psql --username=$${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10
  
  db:
    container_name: db
    image: postgres:18.3-alpine3.23
    restart: always
    env_file: .db.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical
    healthcheck:
      test: "pg_isready --username=$${POSTGRES_USER} && psql --username=$${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  pg_data:
    driver: local
  infisical_pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  infisical: