[service]
deployment = "dev"
environment = "development"
logging_level = "info"

[ai_model]
base_url = "http://127.0.0.1"
base_port = 12434

[ai_model.deployments.ollama_deployments]
models = ["docker.io/ai/llama3.2:1B-Q8_0"]

[ai_model.deployments.ollama_deployments.api]
compatible_api = "ollama"
implemented_endpoints = ["generate", "tags"]

[ai_model.deployments.qwen_deployments]
models = ["docker.io/ai/qwen3:8B-Q4_K_M"]

[ai_model.deployments.qwen_deployments.api]
compatible_api = "qwen"
implemented_endpoints = ["v1/chat/completions", "v1/models"]