[service]
deployment = "dev"
environment = "development"
logging_level = "info"

[ai_model]
base_url = "http://127.0.0.1"
base_port = 12434

[ai_model.deployments.ollama_deployments]
ollama_models = ["docker.io/ai/llama3.2:1B-Q8_0"]

[ai_model.deployments.ollama_deployments.api]
compatible_api = "ollama"
implemented_endpoints = ["generate", "tags"]
