[service]
deployment = "dev"
environment = "development"
logging_level = "info"

[datasource.pl.pap]
name = "pap"
language = "pl"
type = "rss"
url_schema = "https"
root_url = "pap-mediaroom.pl"
data_route = "kategoria"
available_categories = ["biznes-i-finanse", "nauka-i-technologie", "polityka-i-społeczenstwo"]
