name: Build MkDocs and deploy to GH Pages

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Sync .venv
        run: |
          uv sync --all-extras --all-groups

      - name: Build MkDocs
        run: |
          uv run mkdocs build -f ./docs/mkdocs.yml

      - name: Deploy MkDocs
        if: github.event_name == 'push'
        run: |
          uv run mkdocs gh-deploy --clean --force -f ./docs/mkdocs.yml
