name: Run tests

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Sync .venv
        run: |
          uv sync --all-extras --all-groups

      - name: Run e2e tests
        run: |
          uv run pytest -vv ./src/tests/e2e

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Sync .venv
        run: |
          uv sync --all-extras --all-groups

      - name: Run unit tests
        run: |
          PYTHONPATH=./ uv run pytest -vv ./src/tests/unit
